server:
  port: 80

# 关闭缓存
spring:
  thymeleaf:
    cache: false

ctd:
  security:
    authentication:
      login-page: /login/page
      login-processing-url: /login/form
      static-paths:
        - /dist/**
        - /modules/**
        - /plugins/**

      ant-matchers:
        - /user/findById
        - /login/page
        - /code/image

      response-type: json